Added refdump

diff --git a/.github/workflows/build_pages_native.yml b/.github/workflows/build_pages_native.yml
--- a/.github/workflows/build_pages_native.yml
+++ b/.github/workflows/build_pages_native.yml
@@ -24,7 +24,7 @@ jobs:
       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
         with:
-          hugo-version: 'latest'
+          hugo-version: "latest"
           extended: true
       - name: Build
         run: |
@@ -70,6 +70,11 @@ jobs:
           remote_host: ${{ secrets.DEPLOY_HOST }}
           remote_user: ${{ secrets.DEPLOY_USER }}
           remote_key: ${{ secrets.DEPLOY_KEY }}
+      - name: Dump github ref head
+        env:
+          CURR_REF: ${{ github.ref }}
+        run: echo "${CURR_REF}"
+        if: ( ${{ github.ref == 'refs/heads/main' }} || ${{ github.ref == 'refs/heads/staging' }} ) # && ( success() || failure() )  # Remove the && clause when a HTML check is flawless
       - name: Deploy GitHub pages
         uses: JamesIves/github-pages-deploy-action@v4
         if: ( ${{ github.ref == 'refs/heads/main' }} || ${{ github.ref == 'refs/heads/staging' }} ) # && ( success() || failure() )  # Remove the && clause when a HTML check is flawless
